---
# Expose the pythondemo http listener
apiVersion: v1
kind: Service
metadata:
  labels:
    app: pythondemo
  name: pythondemo-example-com
  namespace: pythondemo
  annotations:
    # TODO move these to the values.yaml
    dns.alpha.kubernetes.io/external: pythondemo.example.com
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: tcp
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: '80'
spec:
  externalTrafficPolicy: Cluster
  ports:
  - name: pythondemo-example-com
    nodePort: 30919
    port: 8080
    protocol: TCP
    targetPort: 8080
  - name: pythondemo-example-com-3000
    nodePort: 30920
    port: 3000
    protocol: TCP
    targetPort: 3000
  - name: pythondemo-example-com-3001
    nodePort: 30921
    port: 3001
    protocol: TCP
    targetPort: 3001
  selector:
    app: pythondemo
  sessionAffinity: None
  type: LoadBalancer
---
